format_version: 3
pipelines:
  gs_springboot_pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/moises-ba/gs-spring-boot
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          primeiro_job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - build
                - -x
                - test
                command: gradle
                working_directory: initial
                run_if: passed
