format_version: 3

pipelines:
  gs_springboot_pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/moises-ba/gs-spring-boot
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_app_job:
            timeout: 0
            tasks:
            - exec:
                command: gradle
                arguments:
                - clean
                - build
                - -x
                - test
                working_directory: initial
                run_if: passed
            - exec:
                command: docker
                arguments:
                - build
                - -t
                - moisesba/hello-world:0.0.1
                - .
                working_directory: initial
                run_if: passed    
            - exec:
                command: docker
                arguments:
                - push
                - moisesba/hello-world:0.0.1
                working_directory: initial
                run_if: passed 
        build_docker_image_job:
            timeout: 0
            tasks:
            - exec:
                command: docker
                arguments:
                - build
                - -t
                - moisesba/hello-world:0.0.1
                - .
                working_directory: initial
                run_if: passed    
        push_docker_image_job:
            timeout: 0
            tasks:
            - exec:
                command: docker
                arguments:
                - login
                - -u
                - moisesba
                - -p
                - "{{SECRET:[secret_db][dockerhub_pass]}}"
                working_directory: initial
                run_if: passed    
            - exec:
                command: docker
                arguments:
                - push
                - moisesba/hello-world:0.0.1
                working_directory: initial
                run_if: passed                             
    - deploy_homologacao_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          start_docker_container_job:
            timeout: 0
            tasks:
            - exec:
                command: docker-compose
                arguments:
                - up
                working_directory: initial
                run_if: passed
